spring:
  rabbitmq:
    host: ${rabbit.host:localhost}
    port: ${rabbit.port:5672}
    username: ${rabbit.user:guest}
    password: ${rabbit.password:guest}
  server:
    port: 8082
webapi:
  api-contexts:
    - context: /api
      api-versions:
        - version: v1
          api-resources:
            - get: greeting