spring:
  application:
    name: Rest-API
  rabbitmq:
    host: ${rabbit.host:localhost}
    port: ${rabbit.port:5672}
    username: ${rabbit.user:guest}
    password: ${rabbit.password:guest}
webapi:
  api-contexts:
    - context: /api
      api-versions:
        - version: v1
          api-resources:
            - get: greeting
            - get: users/{id}
              post: users