spring:
  application:
    name: Greeting-Service
  rabbitmq:
    host: ${rabbit.host:localhost}
    port: ${rabbit.port:5672}
    username: ${rabbit.user:guest}
    password: ${rabbit.password:guest}